# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

x = int(input("Ingresa un número: "))
if x > 10:
  print("Mayor que 10")
elif x < 10:
  print("Menor que 10")
else:
  print("Es 10")